sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build docker-demo-app docker-demo-app-tests
script:
  # Run tests
  - docker-compose run --rm -e "CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN" docker-demo-app-tests
  # push master image to ECR
  # env requires: KBC_DEVELOPERPORTAL_USERNAME, KBC_DEVELOPERPORTAL_PASSWORD & KBC_DEVELOPERPORTAL_URL,
  # KBC_DEVELOPERPORTL_APP and KBC_DEVELOPERPORTL_VENDOR
  - docker pull quay.io/keboola/developer-portal-cli-v2:0.0.1
  - export REPOSITORY=`docker run --rm \
    -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL \
    quay.io/keboola/developer-portal-cli-v2:0.0.1 ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
  - docker tag keboola/docker-demo-app:master $REPOSITORY:master
  - eval $(docker run --rm \
    -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL \
    quay.io/keboola/developer-portal-cli-v2:0.0.1 ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
  - docker push $REPOSITORY:master
  # Run live test job on new master image
  # env requires: KBC_STORAGE_TOKEN and KBC_APP_TEST_CONFIG (a token to a test project where the app has a configuration)
  - docker pull quay.io/keboola/syrup-cli:latest
  - docker run --rm -e KBC_STORAGE_TOKEN \
    quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG master
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
notifications:
  email: false
  slack: keboola:fym2t4112jahUATYBYFS3oBS
