version: '2'
services:
  demo-app:
    build: .
    image: keboola/docker-demo-app
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./:/code

  demo-app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: /code/tests/run.sh
