version: '2'
services:
  docker-demo-app:
    build: .
    image: keboola/docker-demo-app
    tty: true
    stdin_open: true

  tests:
    image: keboola/docker-demo-app
    volumes:
      - ./:/code
    entrypoint: /code/vendor/bin/phpunit

  dev:
    image: keboola/docker-demo-app
    volumes:
      - ./:/code
    command: /bin/bash

  xdebug:
    image: keboola/docker-demo-app-xdebug
    build:
      context: .
      dockerfile: docker/xdebug/Dockerfile
    environment:
      - CODECLIMATE_REPO_TOKEN
