version: '2'
services:
  docker-demo-app:
    build: .
    image: keboola/docker-demo-app
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./:/code

  docker-demo-app-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    volumes:
      - ./.git:/code/.git
    command: /code/tests/run.sh
    environment:
      - CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
